[package]
name = "webp"
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO use it
libwebp-sys = { version = "0.6.0", default-features = false, features = [
    "parallel",
] }
image = { version = "0.24.2", default-features = false, features = [
    "jpeg",
    "png",
    "jpeg_rayon",
] }
