[package]
name = "xml"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.22.0", default-features = false, features = [
    "serialize",
] }
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
