[package]
name = "json"
version = "0.1.0"
edition = "2021"

[dependencies]
simd-json = "0.4.15"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
mimalloc = { version = "0.1.29", default-features = false }
