[package]
name = "sql"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "0.8.0", default-features = false, features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
] }
tokio = { version = "1.18.2", default-features = false, features = ["macros"] }
