# https://doc.rust-lang.org/cargo/reference/config.html

[profile.release]
# https://doc.rust-lang.org/cargo/reference/profiles.html#strip
strip = true
# https://doc.rust-lang.org/cargo/reference/profiles.html#lto
lto = true
# https://doc.rust-lang.org/cargo/reference/profiles.html#codegen-units
codegen-units = 1
# https://doc.rust-lang.org/cargo/reference/profiles.html#panic
# panic = 'abort'

# https://doc.rust-lang.org/rustc/platform-support.html
# https://doc.rust-lang.org/reference/linkage.html#static-and-dynamic-c-runtimes
[target.x86_64-unknown-linux-gnu]
rustflags = ["-Dwarnings"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-Dwarnings", "-Ctarget-feature=+crt-static"]

[target.aarch64-apple-darwin]
rustflags = ["-Dwarnings", "-Ctarget-feature=+crt-static"]

[target.x86_64-apple-darwin]
rustflags = ["-Dwarnings", "-Ctarget-feature=+crt-static"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-Dwarnings", "-Ctarget-feature=+crt-static"]
