[package]
name = "chapter03"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "3-1"
path = "src/3_1.rs"

[[bin]]
name = "3-2"
path = "src/3_2.rs"

[[bin]]
name = "3-3"
path = "src/3_3.rs"

[[bin]]
name = "3-5"
path = "src/3_5.rs"
