[package]
name = "image"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.24.1", default-features = false, features = [
    "jpeg",
    "png",
    "webp",
    "jpeg_rayon",
] }
