name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        build_type: ["Debug", "Release"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        if: ${{ matrix.build_type == 'Debug' }}
        run: cargo build --workspace --locked --all-targets

      - name: Build in release mode
        if: ${{ matrix.build_type == 'Release' }}
        run: cargo build --workspace --locked --all-targets --release
