name: Build

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

env:
  RUSTFLAGS: "-D warnings -C target-feature=+aes -C target-cpu=haswell"

jobs:
  build:
    strategy:
      matrix:
        build_type: ["Debug", "Release"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        if: ${{ matrix.build_type == 'Debug' }}
        run: cargo test --workspace --locked --all-targets

      - name: Test in release mode
        if: ${{ matrix.build_type == 'Release' }}
        run: cargo test --workspace --locked --all-targets --release
