name: Clippy

on: [push, pull_request]

env:
  RUSTFLAGS: "-D warnings -C target-feature=+aes -C target-cpu=haswell"

jobs:
  build:
    strategy:
      matrix:
        build_type: ["Debug", "Release"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clippy
        if: ${{ matrix.build_type == 'Debug' }}
        run: cargo clippy --workspace --locked --all-targets -- --deny clippy::all

      - name: Clippy in release mode
        if: ${{ matrix.build_type == 'Release' }}
        run: cargo clippy --workspace --locked --all-targets --release -- --deny clippy::all
