name: Coverage

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

env:
  RUSTFLAGS: "-D warnings -C instrument-coverage"

jobs:
  build:
    strategy:
      matrix:
        platform:
          - { os: "ubuntu-latest", target: "x86_64-unknown-linux-gnu" }

    runs-on: ${{ matrix.platform.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/actions-rs/toolchain
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          default: true
          override: true
          toolchain: stable
          profile: minimal
          components: llvm-tools-preview
          target: ${{ matrix.platform.target }}

      # https://github.com/actions-rs/cargo
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{ matrix.platform.target }} --workspace --locked --all-targets

      # https://github.com/mozilla/grcov#usage
      - name: Generate lcov
        run: |
          curl -fsSL https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-musl.tar.bz2 | tar jxf -
          ./grcov . --binary-path ./target/${{ matrix.platform.target }}/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info

      # https://github.com/codecov/codecov-action#usage
      - name: Upload to codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true
