name: Outdated

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      matrix:
        platform:
          - { os: "ubuntu-latest", target: "x86_64-unknown-linux-gnu" }

    runs-on: ${{ matrix.platform.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/actions-rs/toolchain
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          default: true
          override: true
          toolchain: stable
          profile: minimal
          target: ${{ matrix.platform.target }}

      # https://github.com/Swatinem/rust-cache
      - name: Rust cache
        uses: Swatinem/rust-cache@v1

      # https://github.com/kbknapp/cargo-outdated
      - name: Run cargo outdated
        run: |
          cargo install cargo-outdated
          cargo outdated --workspace --exit-code 1
