name: Outdated

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/kbknapp/cargo-outdated#options
      - name: Outdated
        run: cargo outdated --workspace --exit-code 1
