name: Outdated

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      matrix:
        platform:
          - { os: "ubuntu-latest", target: "x86_64-unknown-linux-musl" }

    runs-on: ${{ matrix.platform.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/actions-rs/toolchain
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          default: true
          override: true
          toolchain: stable
          profile: minimal
          target: ${{ matrix.platform.target }}

      # https://github.com/actions-rs/cargo
      # https://github.com/kbknapp/cargo-outdated
      - name: Run cargo outdated
        uses: actions-rs/cargo@v1
        with:
          command: outdated
          args: --workspace --exit-code 1
