name: Outdated

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/actions-rs/cargo
      # https://github.com/kbknapp/cargo-outdated
      - name: Run cargo outdated
        uses: actions-rs/cargo@v1
        with:
          command: outdated
          args: --workspace --exit-code 1
