name: Rustfmt

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      - name: Rustfmt
        run: cargo fmt --check --all
