name: Rustfmt

on: [push, pull_request]

env:
  RUSTFLAGS: "-D warnings -C target-feature=+aes -C target-cpu=haswell"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      - name: Rustfmt
        run: cargo fmt --check --all
