name: Upload

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/actions-rs/toolchain
      - name: Install stable toolchain
        if: ${{ matrix.os != 'macos-latest' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      # https://github.com/actions-rs/toolchain
      - name: Install stable toolchain (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          default: true

      # https://github.com/actions-rs/cargo
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --locked --all-targets --release

      # https://github.com/actions/upload-artifact
      - name: Upload artifact
        if: ${{ matrix.os != 'windows-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-target
          path: |
            target/release/*
            !target/release/build
            !target/release/deps
            !target/release/examples
            !target/release/incremental
            !target/release/*.d
          if-no-files-found: error

      # https://github.com/actions/upload-artifact
      - name: Upload artifact (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-target
          path: target/release/*.exe
          if-no-files-found: error
