name: Upload

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/actions-rs/toolchain
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      # https://github.com/actions-rs/cargo
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --locked --all-targets --release

      # https://github.com/actions/upload-artifact
      - name: Upload artifact
        if: ${{ matrix.os != 'windows-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-target
          path: |
            target/release/chapter[0-9][0-9]
            target/release/http
          if-no-files-found: error

      - name: Upload artifact
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-target
          path: |
            target/release/chapter[0-9][0-9].exe
            target/release/http.exe
          if-no-files-found: error
